### ISSUE TITLE
SECURITY: merchant wallet address

### ISSUE THREAD

**Issue by carsurfing** [thebitcoincoop/coinos#13]
currently, the merchant wallet address is very easy to change.

ideally changing it would require a re-entry of password (so wise employees don't put their own wallet addys in there:P

**Comment by dykstranet** [comment]
Looks like the logged in user no longer has the ability to change the bitcoin address. However, they do have the ability to withdraw funds. And there is currently no record of withdrawals.  One solution might be to serve up the main POS system without having to log in. Coinos could take payments with no login required. However, admin functions could require login.

**Comment by asoltys** [comment]
If you go to the "Wallet" page, there should now be a settings icon that lets you update your wallet keys.  You should be able to enter a single address or an HD key there.  I should probably make it more obvious or document it better somewhere.  The POS functionality should work without requiring login right now, for example you should be able to see visit a page like https://coinos.io/yummyyards and send a payment without being logged in.

**Comment by dykstranet** [comment]
After going to "Wallet" page, I see "Address or Key" field. What is the format of the key that is automatically generated? What formats are acceptable in that field? BIP 32, Root Seed, or other? Thanks!
