### ISSUE TITLE
Question on Commission/Discount Field in Settings

### ISSUE THREAD

**Issue by geopayme** [thebitcoincoop/coinos#30]
In the settings section can someone explain how the commission/discount field work?

I can't find anywhere any details on the functionality of the fields, even thought many are self explained.

[ Commission (+) / Discount (-) %: ]

**Comment by asoltys** [comment]
This field allows you to either increase or decrease the exchange rate by a given percent.  For example if the exchange rate was $250 and you enter -5 in the Commission/Discount field then 5% will be taken off the exchange rate so it will become 250 - (250 * 0.05) = $237.50
