### ISSUE TITLE
Password Change - Possible Funds Loss

### ISSUE THREAD

**Issue by dykstranet** [thebitcoincoop/coinos#47]
Upon account creation, a bitcoin wallet is created on behalf of the user and encrypted using his/her password. If the user later changes his/her password and does not save the old password, they cannot decrypt the original wallet. Perhaps there could be a warning when changing the user password or re-encrypt the wallet with the new password?

**Comment by dykstranet** [comment]
This appears to be working differently now at the https://coinos.io/ implementation. @asoltys looks like you fixed this?

**Comment by asoltys** [comment]
I think this is working as intended now.  i.e. If you change your password, the system emails you a new encrypted wallet string which replaces the old one.
