### ISSUE TITLE
Firefox Mobile Browser Issue - Android

### ISSUE THREAD

**Issue by dykstranet** [thebitcoincoop/coinos#51]
Strange anomaly using Firefox mobile browser on Android phone.

Getting error "Invalid Address"
[See Screenshot](https://consensusreality.io/coinos/CoinOS_FirefoxMobile_Screenshot_2016.png)

Firefox 48.0

This does not happen in Chrome browser, same phone.

**Comment by asoltys** [comment]
I've reproduced this now with Firefox on my phone.  Need some time to figure out what the issue actually is though.

**Comment by asoltys** [comment]
This had something to do with this issue: https://github.com/feross/buffer/issues/131 and was resolved by rebuilding bitcoinjs-lib with a newer version of browserify.
